Feature/eoepca 27
EOEPCA/um-pdp-engine pull request #21
Opened 2020-09-24 15:16 UTC by joaomatos-dme

2020-09-25 07:01 UTC, hector-rodriguez requested changes

2020-09-25 07:01 UTC, hector-rodriguez commented on tests/examples/policy_rule_c.json
> +            "EQUAL" : {"userName" : "admin" }
Same as the other case: is this change from "user_name" breaking the policy check?

2020-09-25 08:41 UTC, mamuniz commented on tests/examples/policy_rule_a.json
> +                {"EQUAL": {"userName" : "mami"} },
If we get the attributes of the scim handler that Tiago did, it should work with the userName key. We used user_name before Tiago did the scim_handler but we need to test this

2020-09-25 08:54 UTC, joaomatos-dme commented on tests/examples/policy_rule_a.json
> +                {"EQUAL": {"userName" : "mami"} },
I had them all fixed to userName on the branch, must have been broken during the merge. I'll change them.

Although it seems they are not being used anymore? The tests work anyway as they do not use these files

2020-09-28 06:12 UTC, mamuniz approved these changes

2020-09-28 07:15 UTC, hector-rodriguez approved these changes

2020-09-28 07:15 UTC, merged